"""Add gmail and password to candidates

Revision ID: 2b1480d6a3fd
Revises: j8e9f0a1b2c3
Create Date: 2026-07-01 01:17:04.061851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b1480d6a3fd'
down_revision: Union[str, Sequence[str], None] = 'j8e9f0a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('gmail', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'password')
    op.drop_column('candidates', 'gmail')
    # ### end Alembic commands ###
